version: "3"
services:
  web:
    image: evilways/get-started:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
     - "4000:80"
    networks:
     - webnet
  redis:
    image: evilways/redisdb:test
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]    
networks:
  webnet:	
